### ISSUE TITLE
【課題1】typeを用いた実装

### ISSUE THREAD

**Issue by myuuuuun** [myuuuuun/oyama_seminar2016#1]
こういうことでしょうか @oyamad
- [ex01 notebook](http://nbviewer.jupyter.org/github/myuuuuun/oyama_seminar2016/blob/master/exercise/ex01/Ex01.ipynb#type-による実装)

**Comment by oyamad** [comment]
そういうことです．

ちなみに，`throw(DomainError())` のところに行ったら関数が終わるので，`else` はいりません．

**Comment by myuuuuun** [comment]
そうでした
